version: "3"

services:
  filter:
    build: .
    image: dsolab/passets-filter:1.0.0
    container_name: passets-filter
    environment:
      - ELASTICSEARCH_URL=<elasticsearch-host>:9200
      - ELASTICSEARCH_INDEX=logstash-passets
      - THREADS=20
      - CACHE_SIZE=1024
      - DEBUG=0



